/* Contents autogenerated by dyna_tools.py */
const char *lily_dynaload_table[] = {
    "\0\0"
    ,"F\0linenoise\0(String):Either[String,String]"
    ,"F\0history_set_maxlen\0(Integer)"
    ,"F\0history_add\0(String)"
    ,"F\0history_load\0(String):Boolean"
    ,"F\0history_save\0(String):Boolean"
    ,"Z"
};
